home/__init__.py
from flask import Blueprint


home = Blueprint(
    'home',
    __name__,
    url_prefix='/',
    template_folder='templates',
    static_folder='static'
)

home/routes.py
import sys,os,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from . import home
from flask import render_template,session,make_response,request,redirect,url_for,flash
from flask_login import login_user,logout_user,current_user
from pprint import pprint
from models import User,db,RuEng
from sqlalchemy import update
@home.route('/')
def index():
	return render_template('home/index.html',current_user=current_user)

def verifyExt(filename):
	permissible_ext = ['png','PNG','jpeg','JPEG','ico','ICO','webp','WebP','HEIC','helc','jpg','JPG']
	ext = filename.rsplit('.',1)[1]
	if ext in permissible_ext:
		print('раширение файла True')
		return True
	print('раширение файла False')

	return False

def getAvatar():
	from pprint import pprint
	img = None
	img = User.query.filter(User.id == current_user.id).first().avatar
	if not img:
		try:
			with open(home.root_path+'/templates/images/avatar2.png','rb') as f:
				img = f.read()
				return img
		except Exception as e:
			print('Ошибка:',str(e))
		else:
			pass
	return img

@home.route('/profile')
def profile():

	id= current_user.id
	allw = RuEng.query.filter(RuEng.users.any(id=id)).all()
	count = len(allw)
	return render_template('home/profile.html',allw=allw,count=count)

@home.route('/userava')
def userava():
	img = getAvatar()
	if not img:
		return ''
	h = make_response(img)
	h.headers['Content-Type'] = 'image/png'
	return img
@home.route('/upload',methods=['POST','GET'])
def upload():
	if request.method == 'POST':
		file = request.files['file']
		if file  and verifyExt(file.filename):
			try:
				img = file.read()
				user = User.query.filter(User.id == current_user.id).first()
				user.avatar = img
				# update(User).where(User.id==current_user.id).values(avatar = img)
				db.session.commit()

			except Exception as e:
				print('Ошибка:',str(e))
				return redirect(url_for('home.profile'))
		else:
			flash('Недопустимый формат изображения')
			flash("Пожалуйста используйте форматы 'png','PNG','jpeg','JPEG','ico','ICO','webp','WebP','HEIC','helc'")



			
		return redirect(url_for('home.profile'))
	return render_template('home/profile.html')

home/templates/home/index.html
{%extends 'settings/base.html'%}
{%block content%}



<div class="container">
	<div class="row">
			<h1>RuEng - русско-английский словарь</h1>
			
			<h4>Для неавторизованных пользователей доступен демонстрационный набор слов во вкладке <a href="{{ url_for('rueng.common') }}">"Мой словарь"</a></h4>
			<p>
			<h4>Что бы попробовать потренировать доступные слова перейдите во вкладку <a href="{{ url_for('rueng.random') }}">"Случайный порядок"</a></h4>
			<p>
			<h4>Что бы попробовать потренировать написание слова перейдите во вкладку <a href="{{ url_for('rueng.write') }}">"Написание"</a></h4>
			<p>
			<h4>Что бы добавить свои слова, <a href="{{ url_for('settings.signup') }}">авторизуйтесь</a>, тогда появится вкладка "Добавить слово"</h4>
			<p>После этого, сформируеться персональная таблица, в которой будут находится только ваши слова</p>
	</div>
</div>


 







{%endblock%}

home/templates/home/profile.html
{%extends 'settings/base.html'%}
{%block content%}

<div class="container-fluid" >

	<div class="row">
		{%include 'rueng/nav.html'%}
		<div class="col-lg-5 mx-auto">
			{%for msg in get_flashed_messages() %}
				<div class="alert alert-danger"  role="alert">
					{{msg}}
				</div>
			{%endfor%}
		    <div class="text-center card-box">
		        <div class="member-card pt-2 pb-2">
		            <div class="thumb-lg member-thumb mx-auto"><img src="{{ url_for('home.userava') }}" class="rounded-circle img-thumbnail" alt="profile-image"></div>
		            <div class="">
		                <h4>{{ current_user.username }}</h4>
		            </div>
		            <form action="{{ url_for('home.upload')}}" method="POST" enctype="multipart/form-data">
		            	<div class="form-group">
		            		<label for="exampleFormControlFile1">Поменять аватар</label>
		            		 <input type="file" name="file" class="form-contro text-center">
			            	<p><input type="submit" name="Загрузить"class="btn btn-primary mt-3 btn-rounded waves-effect w-md waves-light" id="exampleFormControlFile1">
			            </div>
		            </form>
		            <div class="mt-4">
		                <div class="row"> 
		                    <div class="col-4">
		                        <div class="mt-3">
		                            <h4>{{ count  }}</h4>
		                            <p class="mb-0 text-muted">Всего слов</p>
		                        </div>
		                    </div>
		                    <div class="col-4">
		                        <div class="mt-3">
		                            <h4>0</h4>
		                            <p class="mb-0 text-muted">Обьявления</p>
		                        </div>
		                    </div>
		                    <div class="col-4">
		                        <div class="mt-3">
		                            <h4>Email</h4>
		                            <p class="mb-0 text-muted">{{current_user.email}}</p>
		                        </div>
		                    </div>
		                    <div class="col-6 mx-auto mt-4">
								<table class="table table-dark  mt-3">
									{%if not current_user.is_authenticated%}
										<h3> Здесь представлен демонстрационный набор слов </h3>
									{%endif%}
									<thead>
										<tr>
									  		<th scope="col">#</th>
									  		<th scope="col">Ru</th>
									  		<th scope="col">Eng</th>
									  		<th scope="col">Context</th>


									  	</tr>
									</thead>
									<tbody>
									{%for i in allw%}
										<tr>
									      	<th scope="row">{{i.id}}</th>
									      	<td class="col-3">{{i.ru}}</td>
									      	<td class="col-3" >{{i.eng}}</td>
									      	<td class="text-break col-5">{{i.context}}</td>
									    </tr>
									{%endfor%}
									</tbody>
								</table>
							</div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
</div>






{%endblock%}