settings/__init__.py
from flask import Blueprint

settings = Blueprint('settings',__name__,url_prefix='/rueng',template_folder='templates',static_folder='static')

settings/routes.py
import sys,os,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from . import settings
from flask import redirect,url_for,render_template,request
from forms import RegisterForm_,LoginForm
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from flask_login import login_user,logout_user,current_user
from pprint import pprint
from flask_login import LoginManager,login_required
from models import User
import logging
debug_logger = logging.getLogger('debug_logger')
warning_logger = logging.getLogger('warning_logger')
error_logger = logging.getLogger('error_logger')
@settings.route('/',methods=['POST','GET'])
def signup():
	debug_logger.debug('Enter to signup function')
	form = RegisterForm_()
	if form.validate_on_submit():
		debug_logger.debug('Attempt reguster user')
		user = User.query.filter(User.email == form.email.data).first()
		if user:
			debug_logger.debug('Entered Email already exist email:{}'.format(form.email.data))
			debug_logger.debug('signup закончила работу')
			return render_template('settings/signup.html',form=form,current_user=current_user,alert = 'Такой Email уже занят')
		debug_logger.debug('Attempt reguster user email is not exist')
		try:
			hashed_pass = generate_password_hash(form.password.data,method='sha256')
			new_user = User(email = form.email.data,
						telegramid = form.telegramid.data,
						password =hashed_pass,
						username = form.username.data,
						avatar = None
			)
			db.session.add(new_user)
			db.session.commit()
			app.get_login_manager()
		except:
			logging.exception(f'unsuccessful attempt add new user to database')
		return redirect(url_for('settings.login'))
	return render_template('settings/signup.html',form=form,current_user=current_user)

@settings.route('/login',methods=['POST','GET'])
def login():
	debug_logger.debug('Enter to login function')
	form = LoginForm()
	if request.method=="POST":
		debug_logger.debug('Attempt to login')
		try:
			user = User.query.filter_by(email=form.email.data).first()
		except:
			logging.exception(f'Cant find a user email:{form.email.data}')
		if user:
			try:		
				if check_password_hash(user.password, form.password.data):
					login_user(user, remember=form.remember.data,force=True)
			except:
				logging.exception('Cant start login_user')
			return redirect(url_for('rueng.add'))
		return render_template('settings/login.html',form=form,current_user=current_user,alert='Неправильный пароль или email')
	return render_template('settings/login.html',form=form,current_user=current_user)

@settings.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.index'))

settings/templates/settings/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="text/css" href="{{ url_for('static', filename='vertical_mtnue_style.css') }}" rel="stylesheet">
    <link type="text/css" href="{{ url_for('static', filename='profile_style.css') }}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

   <script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js">
</script>
<script type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.js">
</script>
<script type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython_stdlib.js">
</script>
<script type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython_stdlib.min.js">
</script>
  </head>
    {%include 'settings/navbar.html'%}
  
  <body onload="brython()">
{%block content%}
    
  {%endblock%}
    
    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

settings/templates/settings/login.html
{%extends 'settings/base.html'%}

{%block content%}
<h1 class="row col-1 mx-auto flex-column">Войти</h1>
<div class="container mt-5 mb-5">
  <div class="row col-5 mx-auto flex-column">
    {%if alert%}
      <div class="alert alert-danger" role="alert">
        {{alert}}
      </div>
    {%endif%}
    
    <form class="" novalidate method="POST" action="{{url_for('settings.login')}}">

      <div class="form-group">
      {{ form.email.label() }} {{ form.email(class_='form-control') }}
      </div>

      <div class="form-group">
      {{form.password.label()}} {{form.password(class_='form-control')}}
      </div>

      <div class="form-group">
      {{form.remember.label()}} {{form.remember()}}
      </div>

      <div class="col-12">
        {{ form.submit(class_='btn btn-light') }}
      </div>

    </form>
  </div>
</div>

{%endblock%}

settings/templates/settings/navbar.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('home.index') }}">Home</a>
        </li>
        {%if  current_user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('rueng.add') }}">RuEng</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('rueng.common') }}">RuEng</a>
        </li>    
        {%endif%}

        {%if not current_user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link  "  href="{{ url_for('settings.login') }}" tabindex="-1" aria-disabled="true">Войти</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link "  href="{{ url_for('settings.signup') }}" tabindex="-1" aria-disabled="true">Зарегистрироваться</a>
        </li>
        {%endif%}

        {%if  current_user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link " href="{{ url_for('settings.logout') }}" tabindex="-1" aria-disabled="true">Выйти</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </div>
</nav>

settings/templates/settings/signup.html
{%extends 'settings/base.html'%}

{%block content%}
<h1 class="row col-2 mx-auto flex-column">Регистрация</h1>

<div class="container mt-5 mb-5">

	<div class="row col-5 mx-auto flex-column">
		{%if alert%}
			<div class="alert alert-danger" role="alert">
				{{alert}}
			</div>
		{%endif%}
		<form class="" novalidate method="POST" action="{{url_for('settings.signup')}}">
			{{form.hidden_tag()}}

			<div class="mb-3">
				{{ form.email.label(class_='form-label required',**{'for':'validationEmail'}) }}
				{%if not form.email.errors%}
					 {{ form.email(class_='form-control',**{'type':'text','id':'validationEmail'}) }}
				{% else %}
					{{ form.email(class_='form-control is-invalid',**{'type':'text','id':'validationEmail'}) }}
					<div id="validationEmailFeedback" class="invalid-feedback">
			      		Некорректный email
		   			</div>
		   		{%endif%}	
			</div>

			<div class="mb-3">
				{{ form.telegramid.label(class_='form-label',**{'for':'validationPhone'}) }} 
				{%if not form.telegramid.errors%}
					{{ form.telegramid(class_= 'form-control',**{'id':'validationPhone'}) }}
				{% else %}
					{{ form.telegramid(class_='form-control is-invalid',**{'type':'text','id':'validationEmail'}) }}
					<div id="validationPhoneFeedback" class="invalid-feedback">
			      		Некорректный номер телефона
		   			</div>
		   		{%endif%}
		   	</div>

			<div class="mb-3">
				{{form.username.label(class_='form-label required',**{'for':'validationUsername'})}} 
				{% if not form.username.errors %}
					{{form.username(class_='form-control',**{'id':'validationUsername'})}}
				{% else %}
					{{ form.username(class_='form-control is-invalid',**{'type':'text','id':'validationEmail'}) }}
					<div id="validationUsernameFeedback" class="invalid-feedback">
			      		Имя должно быть больше 4 , но меньше 15 символов
		   			</div>
		   		{%endif%}
			</div>
			<div class="mb-3">
				{{form.password.label(class_='form-label required',**{'for':'validationPsw'})}} 
				{% if not form.password.errors %}
					{{form.password(class_='form-control',**{'id':'validationPsw'})}}
				{% else %}
					{{ form.password(class_='form-control is-invalid',**{'type':'text','id':'validationPws'}) }}
					<div id="validationPwsFeedback" class="invalid-feedback">
			      		Пароль должно быть больше 8 , но меньше 80 символов
		   			</div>
		   		{%endif%}
		   	</div>
			<div class="col-12">
				{{ form.submit(class_='btn btn-light') }}
  			</div>
		</form>
	</div>
</div>
<style type="text/css">
.required:after {
  content:"*";
  color:red;
}</style>


{%endblock%}
{{ form.name(placeholder="Name", **{'ng-model': 'NameModel'}) }}<div class="form-check">
    <input type="radio" class="form-check-input" id="validationFormCheck2" name="radio-stacked" required>
    <label class="form-check-label" for="validationFormCheck2">Toggle this radio</label>
  </div>