rueng/__init__.py
from flask import Blueprint

rueng = Blueprint('rueng',__name__,
				  url_prefix='/rueng',
				  template_folder='templates',
				  static_folder='static'
		)

rueng/routes.py
import sys,os,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from . import rueng
from flask import render_template,current_app
from flask import request,redirect,url_for,session
from app import db
from flask_login import current_user,login_required
from pprint import pprint
from sqlalchemy.orm import scoped_session, sessionmaker
from random import choice
import ast
from .train import Train
from forms import Add_word
import logging
debug_logger = logging.getLogger('debug_logger')

# with rueng.test_request_context():
# 	# print(current_user.id)
# user_id = 
# train = Train(user_id)
@rueng.route('/common',methods=['POST','GET'])
def common():
	from models import RuEng
	from models import Common

	if not current_user.is_authenticated:
		allw = Common.query.all()
		return render_template('rueng/example.html',allw=allw,choice=choice)

	id= current_user.id
	allw = RuEng.query.filter(RuEng.users.any(id=id)).all()
	return render_template('home/profile.html',allw=allw)

	# if request.method =='POST':
		# print(allw)
		# w = Common(ru=request.form['ru'].lower(),eng=request.form['eng'].lower(),context=form.context.data)
		# print(w)
		# db.session.add(w)
		# db.session.commit()
		# return render_template('rueng/example.html',form=form,allw=allw)
	# return render_template('rueng/example.html',allw=allw)


@rueng.route('/',methods=['POST','GET'])
@login_required
def add():
	
	form = Add_word()
	from models import RuEng,User

	id= current_user.id

	allw = RuEng.query.filter(RuEng.users.any(id=id)).all()
	if request.method == "POST":

		user = User.query.filter(User.id.contains(id)).first()
		w = RuEng(ru=form.ru.data.lower(),eng=form.eng.data.lower(),context=form.context.data)
		w.users.append(user)
		current_db_sessions = db.session.object_session(w)
		current_db_sessions.add(w)
		current_db_sessions.commit()

		return redirect(url_for('rueng.add'))
	return render_template('rueng/add.html',current_user=current_user,allw=allw,form=form)


@rueng.route('/all')
@login_required
def all():
	form = Add_word()
	from models import RuEng
	allw = RuEng.query.filter(RuEng.users.any(id=id)).all()
	id = current_user.id

	return render_template('rueng/all.html',current_user=current_user,allw=allw,form=form)

@rueng.route('/all<word_id>')
def del_word(word_id):
	form = Add_word()
	from models import RuEng
	user_id = current_user.id
	sql = r'DELETE FROM word_user WHERE wid={wid} AND uid={uid};'.format(uid=user_id,
																						wid=word_id,form=form
																		)
	db.engine.execute(sql)

	try:
		w = RuEng.query.filter(RuEng.id == word_id).first()
		current_db_sessions = db.session.object_session(w)
		current_db_sessions.commit()
	except:
		logging.exception('Cant commit db before delete word ')
	allw = RuEng.query.filter(RuEng.users.any(id=user_id)).all()
	

	return render_template('rueng/add.html',current_user=current_user,allw=allw,form=form)

@rueng.route('/random')
def random():
	from models import Common

	if not current_user.is_authenticated:
		allw = Common.query.all()
		return render_template('rueng/random.html',err=False,choice=choice,allw=allw)

	user_id = current_user.id
	train = Train(user_id)
	allw = train.get_list_words()
	if len(allw) > 0:
		return render_template('rueng/random.html',err=False,user_id=user_id,choice=choice,allw=allw)
	else:
		return render_template('rueng/random.html',err=True)

# @rueng.route('/random/next_word/')
# def next_word():
# 	user_id = current_user.id
# 	train = Train(user_id)
# 	print('Вывод train',train.get_next_word())
	# return render_template('rueng/random.html',word=word)
	# if len(allw) > 0:
		# allw = allw.pop(allw.index(choice(allw)))
# 		# w = choice(allw)
		# return render_template('rueng/write.html',w=allw,err=False)
	# else:
		# return render_template('rueng/write.html',err=True)

@rueng.route('/write')
def write():
	from models import Common
	if not current_user.is_authenticated:
		allw = Common.query.all()
		return render_template('rueng/write.html',err=False,choice=choice,allw=allw)
	user_id = current_user.id
	train = Train(user_id)
	allw = train.get_list_words()
	if len(allw) > 0:
		return render_template('rueng/write.html',err=False,user_id=user_id,choice=choice,allw=allw)
	else:
		return render_template('rueng/write.html',err=True)



@rueng.route('/write/<eng>',methods=['GET','POST'])
def check_word(eng):
	from models import Common

	if not current_user.is_authenticated:
		allw = Common.query.all()

		if request.method == 'POST':
			if Common.query.filter_by(eng=eng).first().ru == request.form['ru']:
				return render_template('rueng/write.html',allw=allw ,choice=choice,alert='Правильно')
			else:			
				allw = Common.query.filter_by(eng=eng).all() 
				return render_template('rueng/write.html',allw=allw ,choice=choice,alert='Неправильно')

		return render_template('RuEngeng/write.html',allw=allw,err=False,choice=choice)
						
	user_id = current_user.id
	train = Train(user_id)

	if request.method == 'POST':

		if train.check_word(eng,request.form['ru']):
			allw = train.get_list_words()
			
			return render_template('rueng/write.html',allw=allw ,choice=choice,alert='Правильно')
		
		else:
			allw = train.get_list_words(eng)
			return render_template('rueng/write.html',allw=allw ,choice=choice,alert='Неправильно')
 
	return render_template('RuEngeng/write.html',allw=allw,err=False,choice=choice)

rueng/templates/rueng/add.html
{%extends 'settings/base.html'%}

{%block content%}

	<div class="container-fluid">
		<div class="row">
		{%include 'rueng/nav.html'%}
			<div class="col-6 mx-auto mt-4">
				<form method="POST", action="{{ url_for('rueng.add') }}">
					{{form.eng.label()}}
					{{form.eng(class_='form-control')}}
					{{form.ru.label()}}
					{{form.ru(class_='form-control')}}
					{{form.context.label()}}
					{{form.context(class_='form-control',**{'maxlength':'224'})}}
					{{form.submit(class_='btn btn-primary mt-2')}}
				</form>

				<table class="table table-dark  mt-3">
					<thead>
						<tr>
					  		<th scope="col">#</th>
					  		<th scope="col">Ru</th>
					  		<th scope="col">Eng</th>
					  		<th scope="col">Context</th>
					  		<th scope="col"></th>


					  	</tr>
					</thead>
					<tbody>
						{%for i in allw%}
						<tr>
					      	<th scope="row">{{i.id}}</th>
					      	<td class="col-3">{{i.ru}}</td>
					      	<td class="col-3" >{{i.eng}}</td>
					      	<td class="text-break col-5">{{i.context}}</td>
					      	<td class="col-1"><a class="btn btn-outline-danger  btn-sm mr-3" href="{{ url_for('rueng.del_word',word_id=i.id) }}" role="button">Удалить</a></td>
					    </tr>
						{%endfor%}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{%endblock%}

rueng/templates/rueng/example.html
{%extends 'settings/base.html'%}

{%block content%}

	<div class="container-fluid">
		<div class="row">
		{%include 'rueng/nav.html'%}
			<div class="col-6 mx-auto mt-4">
				<table class="table table-dark  mt-3">
					{%if not current_user.is_authenticated%}
					<h3> Здесь представлен демонстрационный набор слов </h3>
					{%endif%}
					<thead>
						<tr>
					  		<th scope="col">#</th>
					  		<th scope="col">Ru</th>
					  		<th scope="col">Eng</th>
					  		<th scope="col">Context</th>


					  	</tr>
					</thead>
					<tbody>
						{%for i in allw%}
						<tr>
					      	<th scope="row">{{i.id}}</th>
					      	<td class="col-3">{{i.ru}}</td>
					      	<td class="col-3" >{{i.eng}}</td>
					      	<td class="text-break col-5">{{i.context}}</td>
					    </tr>
						{%endfor%}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{%endblock%}

rueng/templates/rueng/index.html
{%extends 'settings/base.html'%}

{%block content%}
<h1>Rueng</h1>
{%endblock%}

rueng/templates/rueng/nav.html
			
			<div class="col-4 col-md-4 col-lg-1 navbar-container bg-light text-center"> 
				<nav class="navbar navbar-expand-md navbar-light">
						<ul class="">
							{%if current_user.is_authenticated%}
							<li class="nav-item">
								<a class="nav-link active" aria-current="page" href="{{ url_for('home.profile') }}">Профиль</a>
					        </li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('rueng.add') }}">Добавить слово</a>
							</li class="nav-item">
							{%endif%}
							{%if not current_user.is_authenticated%}

							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('rueng.common') }}">Мой словарь</a>
							</li >
							{%endif%}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('rueng.random') }}">Случайный порядок</a>
							</li >
							<li class="nav-item">
								<a  class="nav-link" href="{{ url_for('rueng.write') }}">Написание</a>
							</li>

						</ul>
				</nav>
			</div>

rueng/templates/rueng/random.html
{%extends 'settings/base.html'%}

{%block content%}

{%if err%}
<div class="container-fluid">
  <div class="row text-center">
    {%include 'rueng/nav.html'%}
    <div class="col-10">
        <h2><a  class="ml-5 text-secondary" href="{{ url_for('rueng.add') }}">Добавьте первое слово</a></h2>
    </div>
  </div>
</div>
{%endif%}
{%if not err%}
{% set word = choice(allw) %}
<div class="container-fluid">
  <div class="row text-center">
    {%include 'rueng/nav.html'%}
    <div class="col-6 mx-auto mt-4 ">
      <div class="mx-auto card text-dark bg-muted mt-5 " style="max-width: 30rem;">
        <h3 class="card-header ">{{ word.eng }}</h3>
        <div class="card-body">
          <p>{{word.context}}</p>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button text-dark bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Показать слово
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <h3>{{word.ru}}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <a class="btn btn-primary" href="{{ url_for('rueng.random') }}" role="button">Next</a>
      </div>
    </div>
  </div>
</div>
{%endif%}

{%endblock%}

rueng/templates/rueng/write.html
{%extends 'settings/base.html'%}

{%block content%}
{%if err%}
<div class="container-fluid">
  <div class="row text-center">
	{%include 'rueng/nav.html'%}
    <div class="col-10">
        <h2><a  class="ml-5 text-secondary" href="{{ url_for('rueng.add') }}">Добавьте первое слово</a></h2>
    </div>
  </div>
</div>
{%endif%}
{% set word = choice(allw) %}
{%if not err%}
<div class="container-fluid text-center">
	<div class="row ">
		{%include 'rueng/nav.html'%}
		<div class="col-4 mx-auto mt-4 justify-content-start">
			{%if alert == 'Неправильно'%}
				<div class="alert alert-warning mt-3" role="alert">
					{{alert}}
				</div>

			{%elif alert == 'Правильно' %}
				<div class="alert alert-success mt-3" role="alert">
					{{alert}}
				</div>
			{%endif%}
			<div>
				<h1>{{word.eng}}</h1>
				<p>{{word.context}}</p>
				<div class="accordion" id="accordionExample">
					<div class="accordion-item">
						<h2 class="accordion-header" id="headingOne">
							<button class="btn btn-light text-dark bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
								Показать слово
							</button>
						</h2>
						<div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
							<div class="accordion-body">
								<h1>{{word.ru}}</h1>
							</div>
						</div>
					</div>
				</div>
					<form action="{{ url_for('rueng.check_word', eng=word.eng) }}" method="POST">
						<input class="form-control mt-3  mb-3" name='ru' type="text" placeholder="Русская версия">
						<button type="submit" class="btn btn-primary">Проверить</button>
					</form>
				
				<a class="btn btn-secondary mt-3" href="{{ url_for('rueng.write') }}" role="button">следующее слово</a>
			</div>
		</div>
	</div>
</div>
{%endif%}
{%endblock%}